version: '3.2'

services:

  php:
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/app
      - ./docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks: 
      - default

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - 70:70
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks: 
      - default

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default


  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret